# SITE CONFIGURATION
# baseurl: "/"
url: "https://pbh.dev"
title: PBH Apps # site's title
description: "Apps for iOS and Mac" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: PBH.dev # blog's title
  avatar: assets/img/icon.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: Welcome to PBH.dev
  header_feature_image: assets/img/banner.jpg
  footer_text: >
    Copyright © 2019 Peter B. Hedlund

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "phedlund"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:
  
  # Sharing options
  share_buttons:
    facebook:
    twitter:
    google_plus:
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin:
    wordpress:
    email:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: # Enable if using math markup
  
  special_page:
    privacy:
      icon: "lock"
      enabled: true
    contact:
      icon: "envelope"
      enabled: true
    search: 
      icon: "search"
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# apps
collections:
  apps:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - type-on-strap.gemspec
  - LICENSE
  - README.md
  - screenshot.png - 
  - package.json
  - node_modules
  - gulpfile.js
  - lightbox2/*.md
  
